## Stack LEMP (Linux (E)Nginx MySQL/MariaDB PHP)

version: '3.8'

services:
  nginx:
    image: vavyskov/nginx:${NGINX_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    hostname: ${PROJECT_HOSTNAME}
    volumes:
      - ../..:${PROJECT_ROOT}
      ## Custom certificates (set path also in dynamic/certificates.yml)
      - ../../../docker-environment/.docker/dev/certificates:/etc/ssl/certificates:ro
    depends_on:
      - php
    environment:
      NGINX_ROOT: ${NGINX_ROOT}
      PROJECT_HOSTNAME: ${PROJECT_HOSTNAME}
      FASTCGI_HOSTNAME: ${COMPOSE_PROJECT_NAME}_php
      CERTIFICATE_PATH: ${CERTIFICATE_PATH}
      CERTIFICATE_FILENAME: ${CERTIFICATE_FILENAME}
      CERTIFICATE_KEYNAME: ${CERTIFICATE_KEYNAME}
    ports:
      - target: 80
        published: ${NGINX_PORT}
    networks:
      - frontend_network
      - backend_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    labels:
      - traefik.enable=true
      - traefik.http.services.${COMPOSE_PROJECT_NAME}_nginx.loadbalancer.server.port=80
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}_nginx.rule=Host(`${PROJECT_HOSTNAME}`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}_nginx.tls=true

  mariadb:
#    image: mariadb:${MARIADB_VERSION}
    image: wodby/mariadb:${MARIADB_TAG}
    container_name: ${COMPOSE_PROJECT_NAME}_mariadb
    environment:
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_czech_ci"]
    volumes:
      #- ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mariadb_data:/var/lib/mysql
    ports:
      - target: 3306
        published: ${MARIADB_PORT}
    networks:
      - database_network
      - project_network
    deploy:
      replicas: 1

networks:
  frontend_network:
    external: true
  backend_network:
    external: true
  database_network:
    external: true
  project_network:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_network

volumes:
  mariadb_data:
    name: ${COMPOSE_PROJECT_NAME}_mariadb_data
